# version: '3.8'

services:

  milvus-db:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus-db
    ports:
      - "${MILVUS_PORT:-19530}:19530"
    environment:
      - MILVUS_HOST=${MILVUS_HOST:-milvus-db}
      - MILVUS_PORT=${MILVUS_PORT:-19530}
    volumes:
      - milvus-data:/var/lib/milvus
    restart: unless-stopped

  ollama-llm:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-models:/root/.ollama
    command: "serve"
    restart: unless-stopped

  rag-api:
    build: .

    # For debugging
    # user: root

    ports:
      - "${RAG_API_PORT:-8001}:8001"
    environment:
      - MILVUS_HOST=${MILVUS_HOST:-milvus-db}
      - MILVUS_PORT=${MILVUS_PORT:-19530}
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama-llm}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
    depends_on:
      milvus-db:
        condition: service_started
      ollama-llm:
        condition: service_started
    volumes:
      # - ./data:/app/data
      - rag-data:/app/data
    restart: unless-stopped

  chatbot-ui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "${CHATBOT_UI_PORT:-3000}:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL:-http://ollama-llm:11434/api}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_DB=milvus
      - MILVUS_HOST=${MILVUS_HOST:-milvus-db}
      - MILVUS_PORT=${MILVUS_PORT:-19530}
    depends_on:
      rag-api:
        condition: service_started
    restart: unless-stopped

volumes:
  rag-data:
  milvus-data:
  ollama-models:
  open-webui-data:
