name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Downgrade pip to <24.1 for textract compatibility
        run: python -m pip install "pip<24.1"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Milvus
        run: |
          docker run -d --name milvus-db -p 19530:19530 -p 9091:9091 milvusdb/milvus:v2.4.3

      - name: Wait for Milvus to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 19530; then
              echo "Milvus is ready!"
              exit 0
            fi
            echo "Waiting for Milvus..."
            sleep 10
          done
          echo "Milvus did not become ready in time."
          exit 1

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        env:
          MILVUS_HOST: localhost
          MILVUS_PORT: 19530
          PYTHONPATH: backend
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest backend/tests -m "not integration"

      - name: Print Milvus logs
        if: failure()
        run: docker logs milvus-db

      - name: Debug Milvus health endpoint
        run: |
          nc -zv localhost 19530